#cloud-config
users:
  - name: oereb
    shell: /bin/bash
package_upgrade: false
runcmd:
  - apt update
  - apt-get install -y zip unzip vim git build-essential
  - usermod -aG docker oereb
  - runuser -l oereb -c 'curl -s "https://get.sdkman.io" | bash'
  - runuser -l oereb -c 'source /home/oereb/.sdkman/bin/sdkman-init.sh && sdk install java 22.2.r11-grl && sdk install gradle 5.1.1'
  - runuser -l oereb -c ''
  - runuser -l oereb -c 'mkdir /home/oereb/apps/'
  - runuser -l oereb -c 'wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.1.1.zip -O /home/oereb/apps/jmeter.zip'
  - runuser -l oereb -c 'unzip /home/oereb/apps/jmeter.zip -d /home/oereb/apps/jmeter'
  - runuser -l oereb -c 'mkdir --mode=0777 /home/oereb/oereb-pgdata'


